# Site settings
title: The Codeteur
header-img: img/home-bg.png
email: mollykathrynnelson@gmail.com
copyright_name: mollykn
description: > # this means to ignore newlines until "baseurl:"
  Updates from a Jane learning to program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mollykn
learn_profile: mollykn
email_username: mollykathrynnelson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
